language: en
pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
  OOV_token: oov
  token_pattern: (?u)\b\w+\b
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 5
  ranking_length: 5
- name: DucklingEntityExtractor
  url: http://duckling.rasa.com:8000
  dimensions:
  - email
  - number
  - amount-of-money
- name: EntitySynonymMapper
- name: ResponseSelector
  retrieval_intent: out_of_scope
  scale_loss: false
  epochs: 5
- name: ResponseSelector
  retrieval_intent: faq
  scale_loss: false
  epochs: 5
- name: ResponseSelector
  retrieval_intent: chitchat
  scale_loss: false
  epochs: 5
- name: FallbackClassifier
  threshold: 0.7
policies:
- name: TEDPolicy
  max_history: 5
  epochs: 10
  batch_size:
  - 32
  - 64
- max_history: 6
  name: AugmentedMemoizationPolicy
- name: RulePolicy
  core_fallback_threshold: 0.3
  core_fallback_action_name: "action_default_fallback"
  enable_fallback_prediction: True
