pipeline:
- name: nlp_spacy
- name: tokenizer_spacy
- name: intent_featurizer_spacy
- name: ner_crf
- name: ner_spacy
  features:
  - - low
    - title
    - upper
  - - bias
    - low
    - prefix5
    - prefix2
    - suffix5
    - suffix3
    - suffix2
    - upper
    - title
    - digit
    - pattern
    - pos
    - pos2
  - - low
    - title
    - upper
- name: intent_classifier_sklearn
language: en
