[tool.black]
line-length = 88
target-version = ['py36']
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.pytest_cache
    | build
    | dist
  )/
)
'''

[build-system]
requires = ["setuptools>=30.3.0", "wheel"]
build-backend = "setuptools.build_meta"