name: Continuous Integration
on:
  push:
    branches:
    - master

jobs:
  docker:
    name: Build Action Server Docker Image
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: oakela

    steps:
      - name: Checkout git repository 🕝
        uses: actions/checkout@v2

        - name: Authenticate into Google Cloud Platform
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '275.0.0'
          service_account_key: ${{ secrets.GCLOUD_AUTH }}

        - name: Configure Docker to use Google Cloud Platform
          run: |
            gcloud auth configure-docker

        - name: Pull Latest Image
          run: |
            docker pull gcr.io/replicated-test/rasa-demo:latest || true

        - name: Set Build ID from PR Ref
          run: echo ::set-env name=BUILD_NUMBER::$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")

        - name: Build Image
          run: |
            docker build -t gcr.io/replicated-test/rasa-demo:pr$BUILD_NUMBER -t gcr.io/replicated-test/rasa-demo:latest --cache-from gcr.io/replicated-test/rasa-demo:latest .
        
        - name: Push PR Image to Google Cloud Container Registry
          run: |
            docker push gcr.io/replicated-test/rasa-demo:pr$BUILD_NUMBER
