name: Train and Upload

on:
  push: 
    branches:
    - main

jobs:
  train-upload-model:
    name: Train and Upload Model to Rasa X
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - id: files
      uses: jitterbit/get-changed-files@v1
    - name: set_training
      if: |
          contains(  steps.files.outputs.all, 'data/' )
          || contains(  steps.files.outputs.all, 'config.yml' )
          || contains(  steps.files.outputs.all, 'domain.yml' )
      run: echo "RUN_TRAINING=true" >> $GITHUB_ENV
    - name: Set up Python 3.7
      if: env.RUN_TRAINING == 'true'
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      if: env.RUN_TRAINING == 'true'
      run: |
          make install-dev
    - name: Train Model
      if: env.RUN_TRAINING == 'true'
      working-directory: ${{ github.workspace }}
      run: |
        rasa train
    - name: Upload model
      if: env.RUN_TRAINING == 'true'
      env:
        RASA_X_API_TOKEN: ${{ secrets.RASA_X_API_TOKEN }}
      working-directory: ${{ github.workspace }}
      run: |
        model_path=`ls models/*.tar.gz | head -n 1`
        curl -k -F "model=@${model_path}" "https://website-demo.rasa.com/api/projects/default/models?api_token=${RASA_X_API_TOKEN}"

